import Foundation

/// Per-(sport, position, stat, season-year) distributions used by era-adjusted scoring.
/// Generated by `tools/ingest` (`baselines.py`) from the full raw season pull — not the
/// curated catalog, which is too thin per year — and bundled as `stat_baselines.json`. The
/// population is position-aware so a WR is judged against receivers, not the whole league.
/// Until that artifact ships, the catalog is empty and era-adjustment falls back to fixed.
struct StatBaselines {

    struct Stat: Equatable {
        let mean: Double
        let std: Double
        let count: Int
    }

    /// Keyed "sport:position:stat:year" → distribution.
    private let table: [String: Stat]
    /// Cross-era pooled mean per "sport:position:stat" (count-weighted over all years).
    /// Backs the era *volume index* used by era-adjusted fantasy points.
    private let globalMeans: [String: Double]

    init(table: [String: Stat] = [:]) {
        self.table = table
        var sums: [String: (weighted: Double, n: Double)] = [:]
        for (k, s) in table {
            // Drop the trailing ":year" to bucket by (sport:position:stat).
            guard let cut = k.range(of: ":", options: .backwards) else { continue }
            let base = String(k[k.startIndex..<cut.lowerBound])
            let n = Double(s.count)
            let prev = sums[base] ?? (0, 0)
            sums[base] = (prev.weighted + s.mean * n, prev.n + n)
        }
        globalMeans = sums.mapValues { $0.n > 0 ? $0.weighted / $0.n : 0 }
    }

    func lookup(sport: Sport, position: String, stat: String, year: Int) -> Stat? {
        table[Self.key(sport: sport.rawValue, position: position, stat: stat, year: year)]
    }

    /// Count-weighted mean of a stat across every era in the catalog — the reference the era
    /// volume index normalizes against. Nil if the stat isn't in the baselines.
    func globalMean(sport: Sport, position: String, stat: String) -> Double? {
        globalMeans["\(sport.rawValue):\(position):\(stat)"]
    }

    static func key(sport: String, position: String, stat: String, year: Int) -> String {
        "\(sport):\(position):\(stat):\(year)"
    }

    var isEmpty: Bool { table.isEmpty }

    // MARK: - Loading

    /// Loads the bundled `stat_baselines.json`. Shape: a flat array of rows
    /// `{ "sport", "stat", "year", "mean", "std", "count" }` (plain decoder).
    static func loadBundled() -> StatBaselines {
        guard let url = Bundle.main.url(forResource: "stat_baselines", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let rows = try? JSONDecoder().decode([Row].self, from: data) else {
            return StatBaselines()
        }
        var table: [String: Stat] = [:]
        table.reserveCapacity(rows.count)
        for r in rows {
            table[key(sport: r.sport, position: r.position, stat: r.stat, year: r.year)] =
                Stat(mean: r.mean, std: r.std, count: r.count)
        }
        return StatBaselines(table: table)
    }

    private struct Row: Decodable {
        let sport: String
        let position: String
        let stat: String
        let year: Int
        let mean: Double
        let std: Double
        let count: Int
    }
}
