import Foundation

/// What the app tells players about a release, in-app — the "OPM" surface, presented by
/// `Notelet` (vendored, see `ThirdParty/Notelet`).
///
/// ## The two rules
///
/// 1. **Every slide carries a component from the code the update changed.** Not a screenshot,
///    not an icon standing in for the idea: the artwork in `Resources/OPM/` is rendered from the
///    shipping views by `OPMSlideGalleryTests`, so it is regenerated by running a test and a
///    change to it shows up as a diff in review. A change with nothing real to show does not get
///    a slide — `1.8.0`'s Grid load fix is the worked example: it made opening The Grid roughly
///    250x smaller on the wire, which is the most valuable thing in the release and is also
///    completely invisible, and the only Grid board renderer in the repo is a test stand-in
///    rather than shipping code. Two honest slides beat three with one hollow one.
/// 2. **The message is one line, at most `messageLimit` characters.** Pinned by
///    `UpdateNotesTests`, so a slide that grows into a paragraph fails the build rather than
///    shipping. This is a slideshow someone taps through on the way to playing, not a changelog.
///
/// ## Who sees it
///
/// Upgraders only. `RootView` marks the current version as seen when a fresh install finishes
/// onboarding, so someone who has been in the app for ninety seconds is never told what changed
/// in the only version they have ever run.
enum UpdateNotes {

    /// The cap from rule 2 above.
    static let messageLimit = 50

    /// One slide: a rendered component and the single line that goes under it.
    struct Slide {
        /// Basename of the PNG in `Resources/OPM/`, rendered by `OPMSlideGalleryTests`.
        let artwork: String
        /// Shown under the artwork. English here is also the string-catalog key, matching how the
        /// rest of the app localizes (keys are the English text).
        let message: String
    }

    /// Keyed by `CFBundleShortVersionString` — Notelet matches on exactly that, so the key has to
    /// track `MARKETING_VERSION` in the pbxproj. A version with no entry simply shows nothing,
    /// which is the right default for a release that is only fixes.
    ///
    /// **Key the release that ships the slides, not the one that shipped the feature.** These
    /// two describe work that went out in 1.8.0, but 1.8.0 (build 45) was already in review
    /// before this surface existed, so a "1.8.0" key here would match no build any user can
    /// install and the whole sheet would silently never appear. `UpdateNotesTests`'
    /// `testCurrentBundleVersionHasNotes` is the guard: bump `MARKETING_VERSION` without adding
    /// an entry and the suite fails.
    static let byVersion: [String: [Slide]] = [
        // The three biggest player-facing changes of the last month, in the order a player meets
        // them: a whole new mode, then the format they play most, then where everything lives.
        // Deliberately *not* the release's largest engineering win — images now download about
        // 25x smaller — because "it got faster" has no component to show and a player who has to
        // be told about a speed-up did not feel one.
        "1.8.1": [
            Slide(artwork: "opm-puzzle-blitz",
                  message: "Puzzle Blitz: one clock, every format"),
            Slide(artwork: "opm-card-redesign",
                  message: "Player cards, rebuilt as trading cards"),
            Slide(artwork: "opm-formats-first",
                  message: "Every way to play, now at the top"),
        ],
    ]
}

// MARK: - Notelet bridge

extension UpdateNotes {

    /// Resolved artwork URL for a slide.
    ///
    /// Notelet's media item takes a `URL` and loads it through `AsyncImage`, so the art ships as
    /// loose PNGs in the bundle rather than as an asset catalog imageset — an xcassets image has
    /// no URL. `file://` URLs are fine for `AsyncImage`; they go through `URLSession`, which
    /// handles them.
    static func artworkURL(_ slide: Slide) -> URL? {
        Bundle.main.url(forResource: slide.artwork, withExtension: "png")
    }

    /// The notes in the shape Notelet wants.
    ///
    /// A slide whose artwork is missing from the bundle is **dropped**, not rendered with a
    /// broken-image placeholder: an update message that can't show the thing it is describing has
    /// nothing to say, and rule 1 above is the whole point of the surface. `UpdateNotesTests`
    /// pins that every declared slide actually resolves, so dropping is the runtime backstop
    /// rather than the expected path.
    static var noteletNotes: [NoteletVersionNotes] {
        byVersion.map { version, slides in
            NoteletVersionNotes(
                version: version,
                items: slides.compactMap { slide in
                    guard let url = artworkURL(slide) else { return nil }
                    return .media(kind: .image,
                                  url: url,
                                  title: LocalizedStringResource(stringLiteral: slide.message),
                                  // Deliberately empty: the rule is one message per slide, and a
                                  // second line here would quietly become a second message.
                                  description: "")
                }
            )
        }
    }
}
